/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./views/**/*.ejs", "./views/**/*.html", "./views/**/*.css"],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    "text-5xl",
    "text-gray-800",
    "text-gray-600",
    "text-red-500",
    "font-bold",
    "text-center",
    "mb-10",
    "text-lg",

    "bg-green-300",
    "hover:bg-green-500",
    "hover:bg-red-500",
    "transition-all",
    "duration-300",
    "rounded",
    "px-4",
    "py-2",
    "text-white",
    
    // Signup form classes
    "bg-gradient-to-br",
    "from-white",
    "to-gray-50",
    "shadow-2xl",
    "rounded-3xl",
    "border-gray-200",
    "w-16",
    "h-16",
    "bg-gradient-to-r",
    "from-red-500",
    "to-red-600",
    "rounded-full",
    "shadow-lg",
    "w-8",
    "h-8",
    "space-y-5",
    "relative",
    "text-sm",
    "font-medium",
    "mb-2",
    "mb-3",
    "mb-8",
    "mt-1",
    "pl-10",
    "pr-4",
    "focus:border-transparent",
    "transition",
    "duration-200",
    "grid-cols-2",
    "gap-4",
    "peer",
    "sr-only",
    "peer-checked:border-red-500",
    "peer-checked:bg-red-50",
    "hover:border-red-300",
    "peer-checked:text-red-500",
    "w-4",
    "h-4",
    "mt-0.5",
    "bg-gray-50",
    "hover:underline",
    "hover:text-red-600",
    "focus:ring-offset-2",
    "transform",
    "hover:-translate-y-0.5",
    "hover:shadow-xl",
    "pt-6",
    "border-t",
    "gap-2",
    "max-w-lg",
    "pointer-events-none",
    "inset-y-0",
    "left-0",
    "pl-3",
    "shadow-md",
    
    // Login form additional classes
    "justify-between",
    "items-start",
    "flex-wrap",
    
    // Header classes
    "bg-gradient-to-r",
    "to-red-600",
    "shadow-lg",
    "px-4",
    "py-3",
    "space-x-1",
    "space-x-2",
    "group",
    "group-hover:bg-red-100",
    "tracking-tight",
    "text-2xl",
    "rounded-lg",
    "p-2",
  ],
};
